Downgrade python version to 3.8
In newer python versions, csv.writer doesn't support
setting escapechar and quotechar to the same value ('@'):

    ValueError: bad escapechar or quotechar value